### PR TITLE
Enable utilization as module

### PR DESCRIPTION
**Pull request by abejenaru**

### CODE REVIEW

**Comment by bartTC** [comment]
Could you explain the reason behind this?

**Comment by abejenaru** [comment]
> Could you explain the reason behind this?

This allows to also run pip-check as a python module (e.g python -m pip_check), and doesn't break running it as a package.
I'm using python in a locked Windows environment, where running packages directly is restricted.

**Comment by bartTC** [comment]
I'll give it some more tests regarding the pypi build and merge soon.

**Comment by bartTC** [comment]
It doesn't look like the package itself is going to get build. You can test this by running `tox`.

```
py311: commands[1]> pip-check
Traceback (most recent call last):
  File "/private/tmp/tox/pip-check/py311/bin/pip-check", line 5, in <module>
    from pip_check import main
ImportError: cannot import name 'main' from 'pip_check' (/private/tmp/tox/pip-check/py311/lib/python3.11/site-packages/pip_check/__init__.py)
py311: exit 1 (0.16 seconds) /Users/martin/Workspace/pip-check> pip-check pid=32760
```

**Comment by abejenaru** [comment]
Noted, I will run the full test suite

**Comment by bartTC** [comment]
Closing this due to staleness.

**Pull request closed without merging**
