### PR TITLE
Fix #17 -  Add pip --user option support

### LINKED ISSUE #17: Add option to hide system packages - show only user installed ones
To be able to separate system-wide packages (e.g. installed with apt/dnf/rpm/yum/whatever) from the user ones, since system packages have their own updating policy.

### PR DESCRIPTION
**Pull request by XVilka**
Well, it was very easy

### CODE REVIEW

**Comment by bartTC** [comment]
I dont think you want `--user` here but `--local`. See my comment in #17

**Comment by XVilka** [comment]
I think having both would be good.

**Comment by XVilka** [comment]
So what you have decided?

**Comment by bartTC** [comment]
Yep, both would be good. I personally don't see that --user is ever going to be used, its a very rare case IMO but it doesn't hurt to have it in. --local is certainly useful.

**Comment by XVilka** [comment]
Done, added also the support for `--local` argument.

**Pull request merged**
